apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.application.name }}
    managed-by: helm
spec:
  replicas: {{ .Values.application.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      {{- if .Values.application.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.application.serviceAccount.name }}
      {{- end }}
      {{- with .Values.application.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.application.name }}
        image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}"
        imagePullPolicy: {{ .Values.application.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.application.container.port }}
          protocol: TCP
        {{- if .Values.externalSecrets.enabled }}
        envFrom:
        - secretRef:
            name: {{ .Values.externalSecrets.externalSecret.name }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
