{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.application.name }}
    managed-by: helm
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    {{- if .Values.ingress.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.externalDns.hostname }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.application.name }}-svc
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
